### PR TITLE
Upgrade Django to 1.6.10.

### PR DESCRIPTION
**Pull request by pmclanahan**
This is a move from Django 1.5.9 to 1.6.10. I have done this
on bedrock witout issue. It may still be a bit harsh to just
do this here, but 1.5.x is unsuported and there are now unpatched
security issues in the wild. This should allow playdoh users at least
a slightly easier path forward.

Note that I've also moved Django from being checked into the repo to
a submodule. We had issues in the past when the official Django github
repo changed the hashes of the previous mirror. Things are now stable
on github for Django, so this seemes easier to update for now.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@peterbe or @jgmize r?

**Comment by jgmize** [comment]
Thanks @pmclanahan

**Comment by peterbe** [comment]
Just FYI, the reason we, back in the day, stopped doing django as a submodule and do it as an installed (lib/python) package instead was because the submodule is so HUGE. This will make `git submodule update --recursive` slower. But who cares?! :) Sugardough is the new thing and that'll point to a wheel.

**Comment by pmclanahan** [comment]
@peterbe hmm... that is a good point. I'm happy to convert it back to a checked-in lib if we'd prefer. But I agree that HOORAY SUGARDOUGH and PEEP!

**Pull request merged**
